global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-titian-mosaic
  s3bucket: ajfriedm-hclscollab-taskcat-bucket
  regions:
    - eu-west-1
    - us-east-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-titian-mosaict1:
    parameter_input: titian-mosaic-params.t1.json
    template_file: titian-mosaic-master.template
    regions:
      - us-east-1
  quickstart-titian-mosaict2:
    parameter_input: titian-mosaic-params.t2.json
    template_file: titian-mosaic-master.template
    regions:
      - us-east-1
